[tool.logging]
version = 1
incremental = true

[tool.logging.formatters.formatter]
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
default_time_format = "%H:%M:%S"

[tool.logging.root]
# The root logger level holds for every module that doesn't have its own level.
level = "WARNING"

[tool.logging.loggers."__main__"]
# The special module __main__ is the script currently being executed.
level = "INFO"

[tool.logging.loggers."stnu.algorithms.rte_star"]
# Module names containing dots must be fully enclosed in quotes.
level = "WARNING"

[tool.logging.loggers."experiments.aaai25_experiments.run_proactive_approach"]
# Module names containing dots must be fully enclosed in quotes.
level = "INFO"


[tool.logging.loggers."experiments.aaai25_experiments.run_reactive_approach"]
# Module names containing dots must be fully enclosed in quotes.
level = "INFO"

[tool.logging.loggers."stnu.algorithms.call_java_cstnu_tool"]
# Module names containing dots must be fully enclosed in quotes.
level = "WARNING"

[tool.logging.loggers."stnu.java_comparison"]
# Module names containing dots must be fully enclosed in quotes.
level = "WARNING"

[tool.logging.loggers."rcpsp.solvers.check_feasibility"]
# Module names containing dots must be fully enclosed in quotes.
level = "WARNING"

[tool.logging.loggers."classes.stnu"]
# Module names containing dots must be fully enclosed in quotes.
level = "WARNING"